<?php

namespace Database\Seeders;

use App\Models\Course;
use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Carbon\Carbon;

class CourseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $mentors = User::where('role', 'mentor')->get();

        $courses = [
            [
                'name' => 'Fundamental Web Development',
                'description' => 'Pelajari dasar-dasar pengembangan web modern dengan HTML5, CSS3, dan JavaScript. Kursus ini cocok untuk pemula yang ingin memulai karir di bidang web development.',
                'mentor_id' => $mentors->random()->id,
                'image' => 'courses/web-fundamental.jpg',
                'start_date' => Carbon::now()->addDays(5),
                'end_date' => Carbon::now()->addDays(35),
                'quota' => 15,
                'price' => 1500000,
                'status' => 'published',
            ],
            [
                'name' => 'Laravel for Beginners',
                'description' => 'Kuasai framework PHP Laravel dari dasar. Belajar membuat aplikasi web yang powerful dengan Laravel untuk pemula.',
                'mentor_id' => $mentors->random()->id,
                'image' => 'courses/laravel-basic.jpg',
                'start_date' => Carbon::now()->addDays(7),
                'end_date' => Carbon::now()->addDays(37),
                'quota' => 20,
                'price' => 2000000,
                'status' => 'published',
            ],
            [
                'name' => 'UI/UX Design Masterclass',
                'description' => 'Pelajari prinsip desain UI/UX dan implementasinya dalam pembuatan produk digital yang user-friendly dan estetis.',
                'mentor_id' => $mentors->random()->id,
                'image' => 'courses/uiux-master.jpg',
                'start_date' => Carbon::now()->addDays(3),
                'end_date' => Carbon::now()->addDays(33),
                'quota' => 12,
                'price' => 2500000,
                'status' => 'published',
            ],
            [
                'name' => 'React.js Advanced Patterns',
                'description' => 'Tingkatkan kemampuan React.js Anda dengan mempelajari pattern dan best practices dalam pengembangan aplikasi modern.',
                'mentor_id' => $mentors->random()->id,
                'image' => 'courses/react-advanced.jpg',
                'start_date' => Carbon::now()->addDays(10),
                'end_date' => Carbon::now()->addDays(40),
                'quota' => 15,
                'price' => 2800000,
                'status' => 'draft',
            ],
            [
                'name' => 'Mobile App Development with Flutter',
                'description' => 'Buat aplikasi mobile cross-platform dengan Flutter. Pelajari cara membuat UI yang menarik dan performa tinggi.',
                'mentor_id' => $mentors->random()->id,
                'image' => 'courses/flutter-dev.jpg',
                'start_date' => Carbon::now()->addDays(15),
                'end_date' => Carbon::now()->addDays(45),
                'quota' => 18,
                'price' => 3000000,
                'status' => 'published',
            ],
            [
                'name' => 'Data Science Fundamentals',
                'description' => 'Pelajari dasar-dasar data science, analisis data, dan visualisasi menggunakan Python dan library populer.',
                'mentor_id' => $mentors->random()->id,
                'image' => 'courses/data-science.jpg',
                'start_date' => Carbon::now()->addDays(8),
                'end_date' => Carbon::now()->addDays(38),
                'quota' => 20,
                'price' => 3500000,
                'status' => 'published',
            ],
            [
                'name' => 'DevOps Engineering',
                'description' => 'Kuasai praktik DevOps modern dengan Docker, Kubernetes, dan CI/CD pipeline untuk deployment yang efisien.',
                'mentor_id' => $mentors->random()->id,
                'image' => 'courses/devops.jpg',
                'start_date' => Carbon::now()->addDays(12),
                'end_date' => Carbon::now()->addDays(42),
                'quota' => 15,
                'price' => 4000000,
                'status' => 'draft',
            ],
            [
                'name' => 'Digital Marketing Strategy',
                'description' => 'Pelajari strategi pemasaran digital yang efektif untuk meningkatkan presence online dan konversi.',
                'mentor_id' => $mentors->random()->id,
                'image' => 'courses/digital-marketing.jpg',
                'start_date' => Carbon::now()->addDays(6),
                'end_date' => Carbon::now()->addDays(36),
                'quota' => 25,
                'price' => 1800000,
                'status' => 'published',
            ],
            [
                'name' => 'Cybersecurity Essentials',
                'description' => 'Pahami dasar-dasar keamanan siber dan praktik terbaik untuk melindungi sistem dan data dari ancaman.',
                'mentor_id' => $mentors->random()->id,
                'image' => 'courses/cybersecurity.jpg',
                'start_date' => Carbon::now()->addDays(20),
                'end_date' => Carbon::now()->addDays(50),
                'quota' => 15,
                'price' => 3200000,
                'status' => 'published',
            ],
            [
                'name' => 'Cloud Computing with AWS',
                'description' => 'Pelajari layanan AWS untuk membangun dan mengelola infrastruktur cloud yang scalable.',
                'mentor_id' => $mentors->random()->id,
                'image' => 'courses/aws-cloud.jpg',
                'start_date' => Carbon::now()->addDays(25),
                'end_date' => Carbon::now()->addDays(55),
                'quota' => 18,
                'price' => 3800000,
                'status' => 'draft',
            ],
            [
                'name' => 'Machine Learning Basic',
                'description' => 'Pelajari konsep dasar machine learning dan implementasinya menggunakan Python dan scikit-learn.',
                'mentor_id' => $mentors->random()->id,
                'image' => 'courses/ml-basic.jpg',
                'start_date' => Carbon::now()->addDays(18),
                'end_date' => Carbon::now()->addDays(48),
                'quota' => 20,
                'price' => 3500000,
                'status' => 'published',
            ],
            [
                'name' => 'Advanced Database Design',
                'description' => 'Kuasai desain database yang kompleks dan optimasi performa untuk aplikasi skala besar.',
                'mentor_id' => $mentors->random()->id,
                'image' => 'courses/database-advanced.jpg',
                'start_date' => Carbon::now()->addDays(22),
                'end_date' => Carbon::now()->addDays(52),
                'quota' => 15,
                'price' => 2800000,
                'status' => 'published',
            ],
            [
                'name' => 'Blockchain Development',
                'description' => 'Pelajari pengembangan aplikasi blockchain dan smart contract menggunakan Ethereum dan Solidity.',
                'mentor_id' => $mentors->random()->id,
                'image' => 'courses/blockchain.jpg',
                'start_date' => Carbon::now()->addDays(30),
                'end_date' => Carbon::now()->addDays(60),
                'quota' => 12,
                'price' => 4500000,
                'status' => 'draft',
            ],
            [
                'name' => 'Game Development Unity',
                'description' => 'Buat game 2D dan 3D menggunakan Unity Engine. Pelajari fundamental game development.',
                'mentor_id' => $mentors->random()->id,
                'image' => 'courses/unity-game.jpg',
                'start_date' => Carbon::now()->addDays(14),
                'end_date' => Carbon::now()->addDays(44),
                'quota' => 15,
                'price' => 3200000,
                'status' => 'published',
            ],
            [
                'name' => 'Software Testing Automation',
                'description' => 'Pelajari automasi testing menggunakan Selenium dan framework testing modern.',
                'mentor_id' => $mentors->random()->id,
                'image' => 'courses/testing-auto.jpg',
                'start_date' => Carbon::now()->addDays(16),
                'end_date' => Carbon::now()->addDays(46),
                'quota' => 18,
                'price' => 2500000,
                'status' => 'published',
            ],
            [
                'name' => 'Vue.js for Professionals',
                'description' => 'Tingkatkan skill Vue.js Anda dengan mempelajari fitur advanced dan arsitektur aplikasi kompleks.',
                'mentor_id' => $mentors->random()->id,
                'image' => 'courses/vuejs-pro.jpg',
                'start_date' => Carbon::now()->addDays(28),
                'end_date' => Carbon::now()->addDays(58),
                'quota' => 15,
                'price' => 2800000,
                'status' => 'draft',
            ],
            [
                'name' => 'Python for Data Analysis',
                'description' => 'Kuasai analisis data menggunakan Python, Pandas, dan NumPy untuk pengolahan data yang efektif.',
                'mentor_id' => $mentors->random()->id,
                'image' => 'courses/python-data.jpg',
                'start_date' => Carbon::now()->addDays(9),
                'end_date' => Carbon::now()->addDays(39),
                'quota' => 20,
                'price' => 2600000,
                'status' => 'published',
            ],
            [
                'name' => 'iOS App Development',
                'description' => 'Belajar membuat aplikasi iOS menggunakan Swift dan SwiftUI dengan best practices modern.',
                'mentor_id' => $mentors->random()->id,
                'image' => 'courses/ios-dev.jpg',
                'start_date' => Carbon::now()->addDays(35),
                'end_date' => Carbon::now()->addDays(65),
                'quota' => 15,
                'price' => 3800000,
                'status' => 'draft',
            ],
            [
                'name' => 'Network Security',
                'description' => 'Pelajari keamanan jaringan dan implementasi firewall untuk melindungi infrastruktur IT.',
                'mentor_id' => $mentors->random()->id,
                'image' => 'courses/network-security.jpg',
                'start_date' => Carbon::now()->addDays(24),
                'end_date' => Carbon::now()->addDays(54),
                'quota' => 15,
                'price' => 3500000,
                'status' => 'published',
            ],
            [
                'name' => 'Content Creation & SEO',
                'description' => 'Pelajari strategi pembuatan konten yang SEO-friendly dan teknik optimasi untuk peringkat tinggi di mesin pencari.',
                'mentor_id' => $mentors->random()->id,
                'image' => 'courses/seo-content.jpg',
                'start_date' => Carbon::now()->addDays(11),
                'end_date' => Carbon::now()->addDays(41),
                'quota' => 25,
                'price' => 1800000,
                'status' => 'published',
            ],
        ];

        foreach ($courses as $course) {
            Course::create($course);
        }
    }
}
